/**
 * Standardized weather conditions used across all providers
 */
export enum StandardWeatherCondition {
  Blizzard = 'Blizzard',
  Breezy = 'Breezy',
  Clear = 'Clear',
  Cloudy = 'Cloudy',
  Cold = 'Cold',
  Drizzle = 'Drizzle',
  Dust = 'Dust',
  Fair = 'Fair',
  Flurries = 'Flurries',
  Fog = 'Fog',
  FreezingDrizzle = 'Freezing Drizzle',
  FreezingRain = 'Freezing Rain',
  Hail = 'Hail',
  Haze = 'Haze',
  HeavyRain = 'Heavy Rain',
  HeavySnow = 'Heavy Snow',
  Hot = 'Hot',
  Hurricane = 'Hurricane',
  IsolatedThunderstorms = 'Isolated Thunderstorms',
  LightRain = 'Light Rain',
  LightSnow = 'Light Snow',
  Mist = 'Mist',
  Mixed = 'Mixed',
  MostlyClear = 'Mostly Clear',
  MostlyCloudy = 'Mostly Cloudy',
  Overcast = 'Overcast',
  PartlyCloudy = 'Partly Cloudy',
  Rain = 'Rain',
  Sandstorm = 'Sandstorm',
  Showers = 'Showers',
  Sleet = 'Sleet',
  Smoke = 'Smoke',
  Snow = 'Snow',
  Storm = 'Storm',
  Thunderstorms = 'Thunderstorms',
  Tornado = 'Tornado',
  TropicalStorm = 'Tropical Storm',
  Windy = 'Windy',
  Unknown = 'Unknown'
}
