name: Run Tests and Coverage

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run coverage

      - name: Display coverage summary
        run: npx jest --coverage --coverageReporters=text-summary

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage